ax_cxx_compile_stdcxx_11.m4: update for latest version from autoconf archives.
* src/m4/ax_cxx_compile_stdcxx_11.m4: update macro from autoconf archives with
  its latest version.  This includes the following changes from upstream:

  022e5bd4
  ax_cxx_compile_stdcxx_11: add a test for SFINAE with template aliases.

  1fc7f019
  AX_CXX_COMPILE_STDCXX_0X: Fix for -Werror=missing-declarations
  This fixes the following error:
    conftest.cpp:49:14: error: no previous declaration for 'void
    test_template_alias_sfinae::test()' [-Werror=missing-declarations]

  d7502e78
  AX_CXX_COMPILE_STDCXX_11: fix test for for clang with [-Werror,-Wunused-variable]
  See https://savannah.gnu.org/patch/index.php?8608 for further details.

  db244e7d
  ax_cxx_compile_stdcxx_11.m4: Support HP aCC
  This compiler needs +std=c++11 to enable C++11 mode:
  http://h21007.www2.hp.com/portal/download/files/unprot/aCxx/PDF_Release_Notes/769149-001.pdf

  ecfc5895
  Check for attribute support with C++11 macro
  Some compilers pass the other tests while not implementing this
  part of the C++11 specification. The test used also does not
  cause warnings with GCC or Clang, and can be used with -Werror.

  e15c34ed
  AX_CXX_COMPILE_STDCXX_11: Support for Cray's crayCC compiler (CCE 8.4)
  Cray Compilation Environment 8.4 has full C++11 support through
  "-h std=c++11" command line switch that we didn't test against